### ISSUE TITLE
Failure to start with error 0xc000000d (Win8/Win10 32-bit, >4GB RAM)

### ISSUE THREAD

**Issue by mcb30** [ipxe/wimboot#15]
Raised from #13 

The following `.yml` file defines a test case that can reproduce the problem:

```yaml
name: Windows 10 (High RAM, 32-bit)
version: win10
arch: x86
memory: 5120
logcheck:
  - 'Found initrd at \[0x[0-9a-f]{8},0x[8-9a-f][0-9a-f]{7}\)'
  - 'Placing initrd at \[0x[0-9a-f]{8},0x[0-7][0-9a-f]{7}\)'
  - 'Placing initrd at physical \[0x[1-9a-f][0-9a-f]{8,},'
```

This test fails for Windows 10 (or Windows 8.1) with a `0xc000000d` error:
![c000000d](https://user-images.githubusercontent.com/692245/108595498-132e4000-7378-11eb-90b0-786042fcbd6e.png)

The test passes if using any 64-bit version of Windows, or if using 32-bit Windows 7.
